---
apiVersion: v1
kind: Namespace
metadata:
    name: prod
    labels:
    name: prod
---        
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
  namespace: prod
spec:
  limits:
  - max:
      #un giga maximo para todos los contedores
      memory: 1Gi
      cpu: 1
    min:
      #100 MB
      memory: 100M
      cpu: 100m
    type: Container
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
  namespace: prod
  labels:
    app: backend
    env: dev
spec:
  containers:
    - name: cont1
      image: nginx:alpine
      resources:
        limits:
          memory: 500M
          cpu: 0.5
        requests:
          memory: 400M
          cpu: 0.3



