---
apiVersion: v1
kind: Namespace
metadata:
    name: prod
    labels:
    name: prod
---        
apiVersion: v1
kind: LimitRange
metadata:
  name: mem-min-max-demo-lr
  namespace: prod
spec:
  limits:
  - max:
      #un giga maximo para todos los contedores
      memory: 1Gi
      cpu: 1
    min:
      #medio giga minimo
      memory: 500Mi
      cpu: 100m
    type: Container
