--- dos pods
apiVersion: v1
kind: Pod
metadata:
  name: podtest2
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
---
apiVersion: v1
kind: Pod
metadata:
  name: podtest3
spec:
  containers:
    - name: contenedor1
      image: nginx:alpine
