apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  # dos pods no podran utilizar el pv, encargado de crear el recurso de 1G
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/test"
