#deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test1
  labels:
    app: backend
#replicasets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  #pod
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: my-service1
  labels:
    app: backend
spec:
  type: NodePort
  #labels para observar
  selector:
    app: backend
  ports:
    - protocol: TCP
      #mapeo de puertos del pod que voy a consumir
      port: 8080
      targetPort: 80
