#deployments
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-test
  labels:
    app: front
#replicasets
spec:
  replicas: 3
  selector:
    matchLabels:
      app: front
  #pod
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: nginx
          image: nginx:alpine
---
apiVersion: v1
kind: Service
metadata:
  name: my-service
  labels:
    app: front
spec:
  type: ClusterIP
  #labels para observar
  selector:
    app: front
  ports:
    - protocol: TCP
      #mapeo de puertos del pod que voy a consumir
      port: 8080
      targetPort: 80
