apiVersion: v1
kind: Pod
metadata:
  name: memory-demo
spec:
  containers:
    - name: memory-demo-ctr
      image: polinux/stress
      resources:
        limits:
          memory: "200Mi"
        requests:
          memory: "100Mi"
      command: ["stress"]
      #pedimos memoria para el proceso directamente
      args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]
